services:
  - type: web
    name: video-backend
    runtime: node
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  - type: web
    name: video-frontend
    runtime: node
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "npm install -g serve && serve -s frontend/dist -l 3000"
    envVars:
      - key: VITE_API_URL
        value: https://video-backend-85pm.onrender.com
      - key: NODE_ENV
        value: production
